### PR TITLE
dgrsd data and R code added

### PR DESCRIPTION
**Pull request by jinshijian**

### CODE REVIEW

**Comment by jinshijian** [comment]
study 34,504,585,627,650,864,1161,1304,1581,2141,2705,2788,2927,3269,3393,5310,5338,5354,5889 latitude and longitude information added

**Comment by bpbond** [comment]
@jinshijian Looking through this, and there's a bunch of things here. Would you like quick feedback this week? Or can it wait until next week for us to sit down together and go through? Thanks.

**Comment by jinshijian** [comment]
Sure, we can discuss it next week.

**Comment by jinshijian** [comment]
Hello Ben, I have reviewed this pull request, it added latitude and longitude of several studies. Can I merge this pull request?

**Pull request closed without merging**
